### ISSUE TITLE
How to test vandium api gateway using lambda-tester

### ISSUE THREAD

**Issue by scorsi** [vandium-io/vandium-node#38]
Hi,

I'm trying to test my vandium api gateway using the vandium-io/lambda-tester.

`handler.js`
```javascript
import vandium from 'vandium';

// WORKING WITH LAMBDA-TESTER
export const handler = (event, context, callback) => {
  callback(null, {
    statusCode: 200,
    body: `Go Serverless v1.0! Your function executed successfully!`
  })
};

// NOT WORKING
export const handler = vandium.api()
  .GET(() => `Go Serverless v1.0! Your function executed successfully!`);
```

`tests/handler.spec.js`
```javascript
'use strict';

var expect = require('chai').expect;

var LambdaTester = require('lambda-tester');

var myLambda = require('../handler.js');

describe('hello', () => {
  it('no event', () =>
    LambdaTester(myLambda.handler)
      .event({})
      .expectResult((result) => {
        console.log(result);
        expect(result.statusCode).to.be.equals(200);
        expect(result.body).to.be.equals('Go Serverless v1.0! Your function executed successfully!');
      }));
});
```

When I try with `vandium` I got the following error.
```
hello › no event

    AssertionError: expected 500 to equal 200

      at tests/handler.test.js:16:41
      at runVerifier (node_modules/lambda-tester/lib/runner.js:178:16)
      at waitForXRay.then (node_modules/lambda-tester/lib/runner.js:291:32)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  console.log tests/handler.test.js:15
    { statusCode: 500,
      headers: {},
      body: '{"type":"Error","message":"Expected event type of apigateway but identified as unknown"}',
      isBase64Encoded: false }
```
When I try without `vandium` I got the following:
```
hello
    ✓ no event (15ms)

  console.log tests/handler.test.js:15
    { statusCode: 200,
      body: 'Go Serverless v1.0! Your function executed successfully! (with a delay)' }
```

Thanks guys ! :)

**Comment by scorsi** [comment]
Ok I found the solution at [dev.to](https://dev.to/clsource/using-vandiumio-to-create-aws-lambda-functions-4ic0).
