### ISSUE TITLE
"vandium": "6.0.0" : SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by vanerleo** [vandium-io/vandium-node#65]
upgrading to vandium 6, results in an error:

```
node_modules/vandium/node_modules/@hapi/joi/lib/errors.js:246
    isJoi = true;
          ^

SyntaxError: Unexpected token =
```

**Comment by richardhyatt** [comment]
What version of node are you using? Should use node >= 12

**Comment by clementAC** [comment]
same here node v12.14.0

**Comment by richardhyatt** [comment]
Are you using node 12 runtime on AWS Lambda? I'm going to release soon as it seems that I put the aws-sdk as a depdendency rather than a dev dependency.

**Comment by clementAC** [comment]
node version set to nodejs12.x

**Comment by richardhyatt** [comment]
have you removed `node_modules` and performed an `npm install`?

**Comment by clementAC** [comment]
Yes and nothing changed. Here is the complete stacktrace

```bash
ERROR in /home/user/project/node_modules/@hapi/joi/lib/errors.js 246:10
Module parse failed: Unexpected token (246:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| exports.ValidationError = class extends Error {
|
>     isJoi = true;
|     name = 'ValidationError';
|
 @ /home/user/project/node_modules/@hapi/joi/lib/index.js 9:15-34
 @ /home/user/project/node_modules/vandium/lib/validation/joi_provider.js
 @ /home/user/project/node_modules/vandium/lib/validation/validation_provider.js
 @ /home/user/project/node_modules/vandium/lib/validation/index.js
 @ /home/user/project/node_modules/vandium/lib/index.js
 @ /home/user/project/client/client.js

ERROR in /home/user/project/node_modules/@hapi/joi/lib/base.js 27:16
Module parse failed: Unexpected token (27:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| internals.Base = class {
|
>     isImmutable = true;                             // Prevents Hoek from deep cloning schema objects
|
|     constructor(type) {
 @ /home/user/project/node_modules/@hapi/joi/lib/types/any.js 5:13-31
 @ /home/user/project/node_modules/@hapi/joi/lib/index.js
 @ /home/user/project/node_modules/vandium/lib/validation/joi_provider.js
 @ /home/user/project/node_modules/vandium/lib/validation/validation_provider.js
 @ /home/user/project/node_modules/vandium/lib/validation/index.js
 @ /home/user/project/node_modules/vandium/lib/index.js
 @ /home/user/project/client/client.js

  Error --------------------------------------------------

  Error: Webpack compilation error, see above
      at /home/user/project/node_modules/serverless-webpack/lib/compile.js:38:19
      at arrayEach (/home/user/project/node_modules/lodash/lodash.js:516:11)
      at Function.forEach (/home/user/project/node_modules/lodash/lodash.js:9342:14)
      at /home/user/project/node_modules/serverless-webpack/lib/compile.js:31:11
      at tryCatcher (/home/user/project/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/user/project/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/user/project/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/user/project/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/user/project/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/user/project/node_modules/bluebird/js/release/promise.js:673:18)
      at /home/user/project/node_modules/bluebird/js/release/nodeback.js:42:21
      at finalCallback (/home/user/project/node_modules/webpack/lib/MultiCompiler.js:254:12)
      at /home/user/project/node_modules/webpack/lib/MultiCompiler.js:277:6
      at done (/home/user/project/node_modules/neo-async/async.js:2931:13)
      at runCompilers (/home/user/project/node_modules/webpack/lib/MultiCompiler.js:181:48)
      at /home/user/project/node_modules/webpack/lib/MultiCompiler.js:188:7
      at /home/user/project/node_modules/webpack/lib/MultiCompiler.js:270:7
      at finalCallback (/home/user/project/node_modules/webpack/lib/Compiler.js:257:39)
      at /home/user/project/node_modules/webpack/lib/Compiler.js:273:13
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
      at AsyncSeriesHook.lazyCompileHook (/home/user/project/node_modules/tapable/lib/Hook.js:154:20)
      at onCompiled (/home/user/project/node_modules/webpack/lib/Compiler.js:271:21)
      at /home/user/project/node_modules/webpack/lib/Compiler.js:681:15
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/user/project/node_modules/tapable/lib/Hook.js:154:20)
      at /home/user/project/node_modules/webpack/lib/Compiler.js:678:31
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/user/project/node_modules/tapable/lib/Hook.js:154:20)
      at /home/user/project/node_modules/webpack/lib/Compilation.js:1423:35
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/user/project/node_modules/tapable/lib/Hook.js:154:20)
      at /home/user/project/node_modules/webpack/lib/Compilation.js:1414:32
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/user/project/node_modules/tapable/lib/Hook.js:154:20)
      at /home/user/project/node_modules/webpack/lib/Compilation.js:1409:36
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/user/project/node_modules/tapable/lib/Hook.js:154:20)
      at /home/user/project/node_modules/webpack/lib/Compilation.js:1405:32
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/home/user/project/node_modules/tapable/lib/Hook.js:154:20)
      at Compilation.seal (/home/user/project/node_modules/webpack/lib/Compilation.js:1342:27)
      at /home/user/project/node_modules/webpack/lib/Compiler.js:675:18
      at /home/user/project/node_modules/webpack/lib/Compilation.js:1261:4
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
      at AsyncSeriesHook.lazyCompileHook (/home/user/project/node_modules/tapable/lib/Hook.js:154:20)
      at Compilation.finish (/home/user/project/node_modules/webpack/lib/Compilation.js:1253:28)
      at /home/user/project/node_modules/webpack/lib/Compiler.js:672:17
      at eval (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
      at /home/user/project/node_modules/webpack/lib/Compilation.js:1185:12
      at /home/user/project/node_modules/webpack/lib/Compilation.js:1097:9
      at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by richardhyatt** [comment]
I re-ran a manual test with vanilla serverless (no plugins) and everything deployed and ran correctly. For the stack trace, it looks like you're using webpack and that's where the error is coming from (looks like the version that's installed is not processing Javascript language features available in 12.x).

What version of serverless and webpack plungin are you using?

Could you share your serverless.yml file or a sanitized version?

**Comment by vanerleo** [comment]
using node12 worked

**Comment by richardhyatt** [comment]
Great - can we close this issue?
